#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another
# page.

# install nginx
apt-get  update
apt-get install -y nginx

# configure the system so that When querying Nginx at its root / with a GET
# request (requesting a page) using curl it returns "Hello world!".
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# configure the /redirect_me
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; " /etc/nginx/sites-available/default

# restart nginx
service nginx restart
